### ISSUE TITLE
Les erreurs s'affichent toujours dans des alert-success

### ISSUE THREAD

**Issue by Madumo** [opencodeca/ocn#102]
Par exemple, lors de la publication d'un post dont le formulaire est incomplet, le message d'erreur s'affichera dans un div aillant la classe alert-success.

**Comment by Madumo** [comment]
Faudrait modifier la classe .alert-danger pour .alert-error dans le css par contre. J'avais utilisé .alert-danger puisque c'était ce que bootstrap utilisait.

**Comment by remi** [comment]
@Madumo Fixé dans 374f360c67b1d085f912506f41b892aaa88cdb0f.
