### ISSUE TITLE
À quand la fête?

### ISSUE THREAD

**Issue by Madumo** [opencodeca/ocn#109]
Salut tout le monde,

Il me semble qu'on a une première version fonctionnelle qui je crois pourrait être mise en ligne. À moins que vous teniez à ce que #108 soit réglé avant?

Donc, je vous pause la question: quand-cé-que-cé qu'on met ça en prod? :birthday:

**Comment by garno** [comment]
C'est prévu pour demain matin :)

**Comment by Madumo** [comment]
Booyah!

**Comment by masterT** [comment]
:)
