### ISSUE TITLE
accès au détail d'un post

### ISSUE THREAD

**Issue by gcauchon** [opencodeca/ocn#110]
J'ai créé mon premier post sur OCN, le seul moyen d'accéder au détail de mon post est de cliqué sur `X commentaires`. Comme je n'ai pas attaché de lien à mon message, n'a pas de `href` alors ça donne l'impression qu'on peut cliqué mais il ne se passe rien...

Je pense qu'on devrait changer le comportement du lien primaire vs. lien externe.

Par exemple sur le premier post de @garno , le titre amènerait sur le détail et `(gist.github.com)` sur le gist.

Qu'est-ce que vous en pensez?

**Comment by jmlacroix** [comment]
De mémoire, sur Hacker News je crois que le titre lorsqu'il n'y a pas de lien mène vers la discussion et sinon vers le post externe. J'opterais pour ce comportement pour ma part.

**Comment by garno** [comment]
Please refresh ;)
