### ISSUE TITLE
La boîte de commentaires devrait se redimensionner quand j'écris

### ISSUE THREAD

**Issue by jmlacroix** [opencodeca/ocn#111]
Pour un commentaire rapide, elle est de la bonne taille. Par contre, quand on écrit quelque chose d'un peu plus long, elle devrait s'adapter au texte.

**Comment by jmlacroix** [comment]
Même chose pour la boîte de description à la création d'un post.

**Comment by jpsirois** [comment]
J’ai remarqué la même chose. Je le fix à l’instant!
