### ISSUE TITLE
Conserver les newline saisis dans les descriptions et commentaires pour permettre de mieux diviser le texte.

### ISSUE THREAD

**Issue by jpsirois** [opencodeca/ocn#114]

**Comment by gcauchon** [comment]
on pourrait aussi supporter le `markdown`? j'ai aucune idée si c'est un "given" ou si c'est overkill?

**Comment by jpsirois** [comment]
Personnellement je suis un fan du markdown, ça pourrait être intéressant je crois si on veux pouvoir formatter les post avec un peu plus de latitude.

**Comment by EtienneLem** [comment]
Ça pourrait être vraiment bien markdown pour du `code syntax`

**Comment by jpsirois** [comment]
Je pense qu’il serait judicieux de s’inspiré du [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown).

**Comment by jpsirois** [comment]
Ou plutôt l’utiliser? https://rubygems.org/gems/github-markdown

**Comment by garno** [comment]
Le problème avec ça c'est que je ne veux pas permettre d'avoir de titre ou autre. Il faudrait whitelister les features de markdown que l'on veut avoir (list, bold, italic). C'est là que ça devient complexe, sinon il y aurait de l'abus pour attirer l'attention ;)

**Comment by louim** [comment]
Tu peux pas juste formater tout le markup de la même façon que du texte? Exemple tous les niveaux de titre on le même format CSS que le "p". Donc tu évite de devoir modifier un document pour retirer les titre si tu veux copier coller et que c'est pas autorisé.

**Comment by garno** [comment]
Ça va faire une belle bouette dans le markup.

**Comment by EtienneLem** [comment]
+1 pour whitelister. Si quelqu’un s’essaye avec un `#`, ben y se passe rien pis y se ramasse avec un `#` dans son texte.

**Comment by jpsirois** [comment]
J’appui le white listing aussi.

**Comment by jbourassa** [comment]
Je connais pas l'API des parsers de Markdown Ruby mais ce serait vraiment cool d'avoir un subset de markdown pour l'italique, bold, lists, blockquote, code. Aussi en accord avec le fait que les niveaux de titres (et potentiellement d'autres élements) ne sont pas appropriés.

:+1:

**Comment by Madumo** [comment]
C'est super simple d'implémenter le markdown dans une app ruby en fait.
Tu peux pas mal tout configurer ce qui est possible ou pas avec un array d'options en paramètre.

http://railscasts.com/episodes/207-syntax-highlighting-revised

**Comment by EtienneLem** [comment]
Pour un autre projet, mais exactement le même concern, Raf vient de me sharer:
- https://github.com/vmg/redcarpet#block-level-calls
- http://dev.af83.com/2012/02/27/howto-extend-the-redcarpet2-markdown-lib.html

Facile!

**Comment by garno** [comment]
Comme l'issue concernait les new lines, je vais la closer et réouvrir un support pour certains éléments du Markdown.  J'ai ajouté un peu de margin pour les `p` et le résultat est beaucoup plus clean:

Exemple: ![](http://f.cl.ly/items/1q4205421z06272y0a3E/Capture%20d%E2%80%99%C3%A9cran%202014-01-14%20%C3%A0%2011.44.44.png)
