### ISSUE TITLE
Le menu mobile ne fonctionne pas

### ISSUE THREAD

**Issue by Madumo** [opencodeca/ocn#115]
Dès qu'on clique sur le menu mobile il ce ferme sans activer le lien.
Ça m'apprendra à avoir seulement testé sur un émulateur.

**Comment by garno** [comment]
@charlesdemers semblait vouloir faire une pull request à ce sujet :) Si tu comptes le faire, assigne-toi la tâche pour éviter d'être 2 à y travailler.

**Comment by charlesdemers** [comment]
Peu importe qui le fait, je suggère d'utiliser quelque chose comme FastClick, ça va éviter d'avoir à faire du feature detection et c'est assez lightweight

**Comment by Madumo** [comment]
J'aimerais bien le fixer moi même :)
Quand mon code plante en prod, j'le prend un peu personnel. :hocho:

**Comment by charlesdemers** [comment]
@Madumo Alright je te laisse ça ;)

**Comment by gcauchon** [comment]
le container semble aussi avoir un height fix, on ne peut donc pas scroller le contenu...

[ocn_mobile](https://f.cloud.github.com/assets/801045/1710680/a943fba8-6137-11e3-88ac-fba911012988.jpg)

**Comment by Madumo** [comment]
J'ai fait pas mal de galipettes pour ne pas avoir deux fois le code du menu dans le html. Le menu c'est la même liste en mobile qu'en desktop, elle est déplacé et placé derrière la page avec du css seulement. Mais bon visiblement ça entraine son lot de problèmes, j'vais revoir ça demain et soumettre une patch

**Comment by Madumo** [comment]
C'était la première fois que j'essayais de faire ça de cette manière
