### ISSUE TITLE
Parser les liens dans les commentaires.

### ISSUE THREAD

**Issue by louim** [opencodeca/ocn#117]
il serait intéressant que les liens dans les commentaires soient parsés pour être cliquable. Ça évite le copier / coller

**Comment by EtienneLem** [comment]
Genre de chose super facile à faire avec [Micky](https://github.com/rafBM/micky)

``` rb
def parse_links(text)
  text = text.dup
  Micky::URI.extract(text).each do |url|
    text.sub! url, link_to(url, url)
  end

  text
end
```

**Comment by garno** [comment]
Entièrement d'accord. Ça te dit de te lancer et de faire une belle pull request :)?
