### ISSUE TITLE
Le favicon n'est pas Retina

### ISSUE THREAD

**Issue by charlesdemers** [opencodeca/ocn#118]
Je peux m'en occuper si quelqu'un a l'image en assez haute résolution. //cc @remiprev

**Comment by remi** [comment]
Est-ce que c’est assez retina ça? :wink:

![](http://opencode.ca/assets/bigicon-a5c12561c217def4e9063da467c4f271.png)

**Comment by charlesdemers** [comment]
Yep! Incoming PR!
