### ISSUE TITLE
Ne pas utiliser de traductions « absolues »

### ISSUE THREAD

**Issue by remi** [opencodeca/ocn#12]
Nos clés de localisations devraient toujours commencer par un `.`.

Ça nous force à construire les éléments des pages de façon constante en créant des _partials_ dont les traductions sont stockées dans un même fichier YAML de localisation.

**Comment by j15e** [comment]
+1

**Comment by j15e** [comment]
ptête mettre ça dans un CONTRIBUTING.md genre? au lieu de garder un issue open

**Comment by remi** [comment]
Je vais le mettre dans `CONTRIBUTING.md` mais mon but n’est pas de garder le issue ouvert. C’est une tâche assignée à moi pour cleaner les traductions actuelles ;)
