### ISSUE TITLE
Automatic login pour le développement

### ISSUE THREAD

**Issue by pier-oliviert** [opencodeca/ocn#122]
Le login par github est vraiment génial mais un peu painful à maintenir en dévelopment. 

Si on pourrait se logger automatiquement en dev ça serait bien pour que les nouveaux venu comme moi puisse jouer avec les features du projet sans avoir à passer par github, ouvrir un port pour le callback oauth, etc.

**Comment by garno** [comment]
Je suis loin d'être un fan de modifier le comportement d'une application selon l'environnement. Ça risque beaucoup plus de causer des problèmes en production et c'est chiant à débugger un coup déployé.

Pour être honnête, ça prend 2 minutes à setupper et j'ai de la misère à comprendre le pain pour la maintenance. Peut-être que si tu élaborais un peu sur les problèmes que ça t'apporte en ce moment, on pourrait voir ce que l'on peut faire ;)

**Comment by pier-oliviert** [comment]
Et bien, je me considère quand même bien versé en rails et j'ai aussi déjà refait l'implémentation Oauth en objective-C. Malgré tout ça, il a tout de même fallu que je réfléchisse à ce que je voulais faire avant de faire le setup github.

Alors, si quelqu'un voudrait commencer à développer pour ce projet en tant que premier projet rails, je suis certain qu'il va trouver le temps long juste à configurer Oauth. Et malheureusement, il faut être logged in pour pouvoir développer sur des actions utilisateurs.

C'est pas bien grave si tu ne veux pas de ça sur ton projet, ça m'a pris environ 15 loc faire ça.

**Comment by garno** [comment]
Ce n'est même pas une question de connaître ou pas OAuth. Il faut simplement se créer une app GitHub et ajouter ton token dans l'environnement. Je vais mettre un walkthrough plus clair dans le README mais je n'ai pas l'intention de modifier le comportement de l'app selon l'environnement. C'est, quant à moi, une mauvaise pratique.

> Et malheureusement, il faut être logged in pour pouvoir développer sur des actions utilisateurs.

Je suis pas certain de comprendre comment je pourrais développer sur des actions utilisateurs **sans** être connecté. C'est la base et ça revient à ce que je disais plus tôt, c'est dangereux de développer dans un contexte différent que celui qui serait utilisé en production.
