### ISSUE TITLE
CSRF vulnerability sur les likes

### ISSUE THREAD

**Issue by pier-oliviert** [opencodeca/ocn#123]
Pas de CSRF token sur les POST like.

**Comment by remi** [comment]
Es-tu certain? `jquery-ujs` ajoute le CSRF token dans ses requêtes. Dans mon inspecteur, j’ai ça :

![](http://i.imgur.com/dKLQKTz.png)

À moins qu’on ne parle pas de la même chose?

**Comment by pier-oliviert** [comment]
J'ai p-e regarde trop vite j'ai pas d'ordi proche. Si javascript est disabled, c'est donc impossible de liker un post?

Envoyé de mon iPhone

**Comment by remi** [comment]
> Si javascript est disabled, c'est donc impossible de liker un post?

Yup!

**Comment by pier-oliviert** [comment]
Ok ferme le ticket debord. J'ai mal checké. C'est bon a savoir pour le jquery ujs, je savais pas!

Envoyé de mon iPhone
