### ISSUE TITLE
Suggestion: Feed rss?

### ISSUE THREAD

**Issue by jeffjrare** [opencodeca/ocn#125]
Salut!

L'idée de rendre disponible un flux rss pour pouvoir s'abonner et lire les nouveaux articles à partir un reader avait-elle été discutée? 

Ce n'est plus super trendy p-e, mais encore beaucoup utilisé quand même, perso je m'en passerais pas.

C'est juste une suggestion, thanks! :)

**Comment by remi** [comment]
:+1: Excellente idée! Connais-tu Ruby? :smile:

**Comment by jeffjrare** [comment]
Je te vois venir là! haha yes je connais bien ;)

Je peux me setuper postgres, bootstraper un fork du code et me permettre de soumettre un pull request dans quelque temps!

Avant tout je regarderais pour voir la façon la plus lightweight possible de générer le feed. Il faut que j'y réfléchisse davantage pour ce qui est du contenu délivré (nouveau article depuis x temps, caching...), mais on se rejase si te va, je vais me setuper et plonger dans le code un peu!

**Comment by garno** [comment]
Voir #126
