### ISSUE TITLE
Stocker le `gravatar_id` que nous retourne GitHub dans User

### ISSUE THREAD

**Issue by remi** [opencodeca/ocn#16]

**Comment by j15e** [comment]
pas besoin vraiment on a juste à faire `Digest::MD5.hexdigest(@user.email)`

**Comment by remi** [comment]
Le `email` du user n’est pas toujours retourné par l’API de GitHub, mais `gravatar_id` oui.

**Comment by j15e** [comment]
ah ouais si le email est privé! good alors!
