### ISSUE TITLE
Convertir les fichiers Haml en ERB

### ISSUE THREAD

**Issue by remi** [opencodeca/ocn#3]
On veut revenir à ERB chez Mirego, ça pourrait être bien de faire http://news.opencode.ca en ERB :smile:

**Comment by EtienneLem** [comment]
:metal: +1

**Comment by j15e** [comment]
+1 en tabarnouche

**Comment by simonprev** [comment]
![1383667399-8396c10428acb12f615b2d73a80b767c](https://f.cloud.github.com/assets/464900/1474842/ea83f754-4633-11e3-819a-f0af939ba2f0.jpg)

**Comment by jbourassa** [comment]
Oh, s'il vous plaît. Pas un grand fan de Haml ici.
