### ISSUE TITLE
Use a more "popular" comment gem

### ISSUE THREAD

**Issue by simonprev** [opencodeca/ocn#30]
More stars, more docs
https://github.com/the-teacher/the_comments

https://github.com/the-teacher/the_comments/blob/master/docs/whats_wrong_with_other_gems.md#why-thecomments-is-better-than-others-gems

**Comment by remi** [comment]
> \6. TheComments has admin UI based on bootstrap 3

Wat?

Sinon, awesome choix! Let’s do this!

**Comment by j15e** [comment]
seems legit

**Comment by garno** [comment]
C'est **huge**, je viens de commencer à l'intégrer pour remplacer [Parole](https://github.com/mirego/parole). Y'a vraiment un shitload de features inutiles pour notre utilisation (i.e. draft, admin, views, etc.).

imho, il serait mieux de modifier un peu Parole pour permettre le threading de commentaires.

**Comment by j15e** [comment]
+1 for home made stuff

**Comment by remi** [comment]
:+1: aussi. Améliorons Parole à la place, au lieu de ditcher des features dans une autre librairie plus complète.
