### ISSUE TITLE
Add super clever algorithm to sort by popularity

### ISSUE THREAD

**Issue by simonprev** [opencodeca/ocn#37]
Ça devrait ressember à ça, tweaké un peu, bien sûr, sur un échantillon de `Post`

``` mysql
((posts.comments_count + posts.like_emotions_count)/power(((unix_timestamp(utc_timestamp())-unix_timestamp(posts.created_at))/60),0.4)) as rank
```

Je suis pas un rocket scientist mais ça devrait nous convenir pour l'instant...

**Comment by simonprev** [comment]
Mettont un exemple de frontpage "popular":
![capture decran 2013-11-06 a 00 18 15](https://f.cloud.github.com/assets/464900/1480245/1cf9ba1a-46a3-11e3-9f42-3f3322f389f0.png)

Les likes comptent pour beaucoup dans l'équation (3x plus que les comments). Mais comme vous pouvez le voir, un post du 5 novembre avec 163 likes dépasse un post du 4 novembre avec 235 likes.

Je vais faire une pull request qui implémente cette algo pour pouvoir le tester dans le vrai website

**Comment by j15e** [comment]
cool ; ps la fonction unix existe pas en postgresql ça va prendre une autre version si on le deploy sur heroku

**Comment by jbourassa** [comment]
Est-ce que y'a une limite de temps? Parce que si le nombre de post devient gros ça sera pas beau sans index, il faudra faire un full table scan à chaque requête. Pas un problème majeur immédiatement, mais éventuellement ça va craquer.

**Comment by j15e** [comment]
Ouin on devrait genre mettre un max 1 mois ou de quoi du genre au départ de la requête

**Comment by frederickdubois** [comment]
Idéalement, assez rapidement tu veux pas faire ta requête en live, tu veux mettre ton résultat en cache un certain temps. 

Probablement qu'un "hard time limit" va donner des résultats étranges. Faudrait trouver une manière de retirer ce qui est vieux ET qui a pas généré d'intérêt. Si on a une red-hot-discussion de 30 jours et qu'elle disparaît d'un coup c'est weird

**Comment by remi** [comment]
> Si on a une red-hot-discussion de 30 jours et qu'elle disparaît d'un coup c'est weird

Donc ça serait cool si l’algorithme prennait en compte le `created_at` des likes et des comments.

**Comment by jbourassa** [comment]
^ Yup. Pas certain de comment faire ça d'une façon rapide / indexé. Surement qu'un de ces clone de reddit (ou un peu de google-fu) peut nous donner une idée.

**Comment by frederickdubois** [comment]
bah, faut juste pas calculer tout en "live"

si on a un worker ou une mise à jour "on event" qui tiens à jour la clé de "hotness" de chaque article asynchronously on devrait être bon

au fond, on voudrait trier sur l'algo pour la liste complète ou juste pour la home page? Si on navigue séquentiellement dans l'app on passe en mode "date only" ou on reste par relevance pour passer à travers tous les posts

sorry, j'ai pas vu encore on en est où, je me bats encore avec mon fucking ordi... :)

**Comment by simonprev** [comment]
Êtes-vous fou? :wink: Là c'est pas pour être platte mais le sorting de popularité sera pas "caché", sera calculé à chaque request et sera basé sur les nombres de likes et comments. On va aussi mettre une limite pour pas mettre la table en entier en mémoire.

Voici l'algo de reddit quand ça a commencé: https://github.com/reddit/reddit/blob/master/sql/functions.sql#L23

Quand le problème sera que la request est lente, on la mettra en cache. Quand la cache sera pas assez performante on la calculera dans un worker.

Le but du sorting est de donné une approximation de populaire, c'est assez différent de ce que reddit fait.

Je vais poster la pull request ce soir et vous pourrez faire des tests de votre côté sur le model `Post` et on tweakera pour que ça donne des résultats qui nous conviennent.

**Comment by jbourassa** [comment]
Pour ré-enchérir sur ce que Rémi dit, on n'a qu'à _touch_ le `updated_at`
et limiter par ça, ça va donner quelque chose de assez garantie rapide
imho. Simple et très peu de downside.

0.02$ canadien

**Comment by simonprev** [comment]
Oui bon point le `updated_at`, will do!

**Comment by garno** [comment]
:+1: sur ce que Simon a dit. On ne sait même pas encore ce qui nous intéresse et qu'est-ce qui rend réellement un article populaire. Il est possible que finalement, les commentaires soient plus importants que les _likes_ ou vice-versa. Ça sert absolument à rien de se _garocher_ dans un algorithme hyper précis, d'utiliser de la cache et d'optimiser en fou. On est pas rendu là imho.

Gardez en tête qu'on _build_ un MVP et que ce _codebase_ va évoluer au fur et à mesure qu'on va voir l'utilisations que la communauté en fera :) Bref, attendons que @ldionne nous ponde un algorithme de la mort qui tue :wink:. Pour le moment, cet algorithme me semble _good enough_.

**Comment by j15e** [comment]
good enough, le prochain argument devrait être une pull request

**Comment by garno** [comment]
Voir _pull request_ https://github.com/opencodeqc/ocn/pull/46
