### ISSUE TITLE
Rédiger un “briefing” du projet dans le README

### ISSUE THREAD

**Issue by remi** [opencodeca/ocn#38]
Ce briefing devrait définir :
- Le but et la motivation de développement du projet
- Les spécifications techniques globales
- Des fonctionnalités à développer pour la première version
- Des fonctionnalités potentielles à ajouter dans le futur
- Un échéancier idéal?

**Comment by garno** [comment]
Voir _pull request_ https://github.com/opencodeqc/ocn/pull/44
