### ISSUE TITLE
Le <title> et ses chameaux.

### ISSUE THREAD

**Issue by EtienneLem** [opencodeca/ocn#4]
Faut s’entendre:
- Ocnews (en ce moment)
- OCNews
- OC News
- OpenCode News

Question qu’on puisse souligner l’erreur aux fautifs.

**Comment by remi** [comment]
En fait, le nom du projet n’est même pas définitif. Mais effectivement ça prendrait un _working title_ constant. Je propose un nom de code générique sans avoir à se soucier de la case. Genre, **OCN**.

**Comment by remi** [comment]
Et par le fait même, je renommerais le repository en `ocn`. C’est fatiguant le `news`, surtout si on veut bâtir une communauté 100% francophone :smile:

**Comment by garno** [comment]
`ocn` it is. Pour le moment ;)

**Comment by garno** [comment]
Pendant que nous y sommes, il serait intéressant de déterminer un nom pour le projet. Comme @remiprev l'a dit, nous voulons une communauté 100% francophone. Il est donc ironique d'utiliser news.opencode.ca même si c'est un peu la norme dans ce genre de communauté.

Avez-vous d'autres idées?

Ce que nous voulons est plus de créer des discussions et débats autour d'un sujet commun: le code. Et aussi un endroit pour partager vos réalisations et vos projets personnels.

Je lance donc quelques idées, gardez en tête qu'on brainstorm donc aucune idée n'est mauvaise. N'hésitez pas à embarquer :)
- nouvelles.opencode.ca
- partage.opencode.ca
- discussion.opencode.ca
- communaute.opencode.ca

**Comment by EtienneLem** [comment]
http://mur.opencode.ca

“Met ça sul mur”
“Check le mur”
“Lol, tu connais pas le mur?”

Ça fait pas mal FB… Quelque chose dans le même concept: etage, coin, abri, toit, tipi, caverne…

**Comment by L-A** [comment]
nouvelles.opencode.ca serait le plus simple/explicite, surtout que le but c'est de se rapprocher d'un concept HN mais qui vise la communauté francophone.

Sinon côté actualités, y'a toujours helicoptere-tva.opencode.ca.

**Comment by jbourassa** [comment]
Je crois que ce que ce projet peut amener à la communauté assez différent d'un news feed, alors je crois que le terme _news / nouvelles_ est pas le meilleur. Quelque chose qui tourne autour du mot communauté serait plus intéressant.

Réflexion:

Communauté est long, alors on pourrait trouver quelque chose de mieux. Pas si fan, mais tout de même:
- mur de @EtienneLem, c'est pas mal
- groupe.opencode.ca
- sup.opencode.ca
- collectif.opencode.ca

**Comment by j15e** [comment]
la taverne? c'est francophone et québecois et ça fait référence à de la bière. mais sinon je vote mur ou collectif

**Comment by garno** [comment]
J'avais pensé à la _taverne_ et j'aimais bien. Par contre, si on pousse un peu, c'est aussi un endroit pour hommes donc peut être considéré sexiste :confused:. Je ne sais pas si la gente féminine serait offensée. Tsé, si on veut être _politically correct_ ;)

**Comment by EtienneLem** [comment]
Ah ouin?

> Au Québec, jusqu'en 1988, l'endroit était réservé exclusivement aux hommes
> Source: [Wikipedia](http://fr.wikipedia.org/wiki/Taverne_%28établissement%29#Les_tavernes_dans_le_monde)

Ben oui toi… t’es vraiment vieux Sam pour savoir ça :older_man: :stuck_out_tongue_winking_eye: . Moi c’est pas du tout la première ce qui me vient en tête. Je sais pas si les gens font cette association?

**Comment by remi** [comment]
La taverne c’est pas que c’est sexiste, c’est que ça me semble trop familier. Pas qu’on veut que ça soit professionnel, mais m’semble ça serait cool si ce n’était pas un mot associé à un endroit où les gens vont prendre un coup :smile:

**Comment by pier-oliviert** [comment]
chevalier-de-colomb.opencode.ca

**Comment by renaudleo** [comment]
Idées random dans la lignée de la collaboration, collectivité et compagnie (vous pouvez clairement voir mon cheminement mental) :
- partage.opencode.ca
- potluck.opencode.ca
- chaudiere.opencode.ca
- ragout.opencode.ca

**Comment by remi** [comment]
> ragout.opencode.ca

I LOL’d.

**Comment by L-A** [comment]
Groupe, Collectif, Global sont des bons noms. J'aime Groupe parce que ça fait un petite distinction entre la communauté et l'événement. Groupe, et Soirée. C'est nice.

scene.opencode.ca? C'est un clin d'oeil à l'événement aussi.

"C'est hot man, mets ça sur la scène."

**Comment by garno** [comment]
Je ne déteste pas l'idée de scene.opencode.ca. C'est effectivement un endroit pour partager sous le _spotlight_.

**Comment by Madumo** [comment]
agora.opencode.ca

**Comment by simonprev** [comment]
carrefour.opencode.ca

**Comment by jipiboily** [comment]
:thumbsup: pour scene.opencode.ca || agora.opencode.ca

@renaudleo: t'as écrit ça juste avant de manger, right? ;)

@EtienneLem: @garno n'est pas le seul à faire cette association...c'est réservé à ceux qui ont attendus des tounes à la radio pendant des heures pour se faire un mixte p-e? Ou reculer une cassette avec un crayon...

:thumbsup: pour l'idée en passant!

**Comment by jpsirois** [comment]
J’aime bien `scene.opencode.ca` aussi.

**Comment by matehat** [comment]
Petite parenthèse, "news" est reconnu dans la plupart des dictionnaires français!

Mais perso, :+1: pour scene.opencode.ca et mur.opencode.ca

**Comment by remi** [comment]
Moi je pense qu’on pourrait aussi continuer d’appeler ça `ocn.opencode.ca`, pour _OpenCode Nouvelles_. Et on continue de prononcer ça _Oh-see-n_, parce que c’est cool :smile:

**Comment by Madumo** [comment]
$(this) ^

**Comment by L-A** [comment]
@remiprev J'étais sûr que tu prononçais ça "Oh Shaun"

![image](https://f.cloud.github.com/assets/861964/1655248/015d5138-5b5f-11e3-9e29-0ed14a66e7a2.png)

**Comment by garno** [comment]
OCN it is.
