### ISSUE TITLE
Pouvoir se créer un compte / se connecter via le login de GitHub

### ISSUE THREAD

**Issue by frederickdubois** [opencodeca/ocn#5]
pas de compte github, pas de login

**Comment by remi** [comment]
C'est pas fait ça?

**Comment by frederickdubois** [comment]
indeed, je viens de voir :)

je voulais juste pas oublié et j'avais pas vu dans la issues list mais vous êtes plus avancés que je pensais 
closing :)

**Comment by j15e** [comment]
Dunno why mais moi ça me fait "ActiveRecord::UnknownAttributeError / unknown attribute: password" quand j'arrive au callback url

**Comment by simonprev** [comment]
Même chose de mon côté, je sais pas pourquoi la table users a une column `encrypted_password`...

**Comment by j15e** [comment]
Probablement un copier/coller d'un autre projet... dans les migrations password a jamais existé pour users, mettre encrypted_password dans le concern ça fix le problème.

**Comment by garno** [comment]
La colonne `encrypted_password` provient de Devise. `password` n'est en effet pas un attribut de user mais une méthode qui sert à définir `encrypted_password`. Bref, la ligne pourrait même être enlevé des attributs puisque le mot de passe ne sert absolument à rien dans un cas comme celui-ci.

Une partie du code provenait d'un exemple de Devise + Omniauth et contient bel et bien `password: ...`. Weird!

**Comment by garno** [comment]
Je viens de pousser un fix.
