### ISSUE TITLE
Parlons design

### ISSUE THREAD

**Issue by garno** [opencodeca/ocn#58]
Si vous êtes tombé sur des _screenshots_ de l'app dans son état actuel ou que vous avez faire un petit _pull_, vous avez constaté que l'accent n'a pas été mis sur le design, ni même sur le _ux_. Puisque nous voulons essayer de lancer la plateforme d'ici le prochain OpenCode, il serait peut-être temps de s'en soucier un peu et d'y penser.

Je tiens énormément à garder le tout très simple et épuré, le _focus_ doit rester sur le contenu et les discussions.

Quelle est votre vision du _look & feel_ de OCN?

Je fais aussi appel aux designers préférés de l'OpenCode, @L-A @tristanlabbe :)

**Comment by j15e** [comment]
Moi je vote contre le CSS

**Comment by garno** [comment]
Puis-je te demander pourquoi?

**Comment by j15e** [comment]
C'était une blague, mais j'avoue qu'elle était pas si drôle, yé tard!

**Comment by garno** [comment]
C'est pas facile à _gager_ sur les interwebs :) J'avais espoir que tu ne sois pas sérieux. Truth is, y'a des puristes qui aimeraient bien que ça soit du plain old html.

**Comment by j15e** [comment]
J'ai mis le CSS inline sur mon site perso pour que ça load plus vite, mais je me suis pas rendu jusqu'à l'enleve ;p

**Comment by EtienneLem** [comment]
2 cents; Si c’est le CSS votre concern pour un (re)design, ya un problème (dans le sens que votre concern est mal placé, non pas que _vous_ avez un problème :stuck_out_tongue_winking_eye:). Peu importe le design y’a toujours moyen de faire du CSS performant, faut juste pas perdre le contrôle.

La grosse différence avec le backend c’est que c’est rarement (disont aisément) _refactorable_ sans vouloir tout recommencer.

Mais stressez vous pas avec ça, y’en a que c’est leur force :wink:

**Comment by j15e** [comment]
C'ÉTAIT UNE JOKE lol

**Comment by EtienneLem** [comment]
I KNOW I KNOW, mais

>  Truth is, y'a des puristes qui aimeraient bien que ça soit du plain old html.

C’était surtout re: ça

**Comment by j15e** [comment]
Plus sérieusement je pense qu'on devrait faire de quoi de plus "user friendly" que HackerNews, on est en 2013, je ferais un site qui look 2013 même si on le fait simple et clean.

Plus spécifiquement, j'aimerais bien ça que le texte soit un peu plus gros et un peu plus lisible. Mais je pense que ça pourrait être bien de garder quelques clin d'oeil à hacker news ou autre comme le ▲ pour upvote.

**Comment by EtienneLem** [comment]
Yup. Je sais pas si on peut aller chercher de l’inspiration sur http://www.readability.com ou encore http://www.instapaper.com, mais je verrais de quoi d’assez épuré et focusé sur la typo avec une seule couleur d’accent (pour les liens, etc.).

**Comment by garno** [comment]
@EtienneLem C'est pas mal ma vision aussi. Il manque juste quelqu'un qui se lance à le faire :) Je pense pas que l'on ai besoin de maquettes pour ça.

**Comment by L-A** [comment]
Bonjour.

**Comment by remi** [comment]
> Bonjour.

:+1:

**Comment by L-A** [comment]
Sur ce point, j'ai un undefined method qui m'empêche de lancer OCN depuis que j'ai pull cette semaine.

C'est `preload_app!` dans `config/puma.rb` qui le déclenche. On peut faire du gros debugging à distance, ou quelqu'un peut me shooter un snapshot HTML utilisable.

**Comment by garno** [comment]
Ah, il y a un problème avec le script de puma. Ça fonctionne si tu fais simplement `bundle exec rails server` au lieu de `bundle exec foreman start`. Je vais fixer ça demain dès que j'ai 2 minutes.

Have fun :)

**Comment by remi** [comment]
> Sur ce point, j'ai un undefined method qui m'empêche de lancer OCN depuis que j'ai pull cette semaine.

C’est réglé. J’ai upgradé puma à sa version la plus récente qui supporte `preload_app!`.

**Comment by L-A** [comment]
`bundle exec puma` maybe?

Tout est up and running, là. Je suis en train de me battre avec Bootstrap. C'est qui qui met des listes partout comme ça? Je dois jouer dans les templates pas mal à date.

**Comment by gcauchon** [comment]
Jumpin in pour vous donner un coup de pouce... je suis loin d'être un artiste designer, mais j'ai un bon instinct et je pense qu'on dois rendre le site le plus _mobile-friendly_ possible. Comme @j15e a dit, une font plus grosse, plus d'espace pour séparé les _blocks_ d'information naturellement et un peu de fine-tuning pour ajuster le layout en fonction des breakpoints de la grille responsive de Bootstrap et ça devrait être A1!

Il ne me reste qu'à comprendre comment setupper le OAuth comme j'ai mentionné dans #94 et je vais être bon pour commencer à me familiariser un peu plus avec rails...

**Comment by plbabin** [comment]
je peux aider avec le design aussi, faudrait juste pas être 6 à travailler là dessus chacun dans notre coin :)

**Comment by plbabin** [comment]
ma proposition pour le design, ça peut être un point de départ, comme ça peut être lancé au poubelle, à vous de choisir :)

![image](https://f.cloud.github.com/assets/203992/1634293/a7d23568-5797-11e3-93aa-6522d4613741.png)

**Comment by gcauchon** [comment]
that's it!

infinite-scroll pour éviter la pagination et les "loading"?

**Comment by remi** [comment]
:-1: pour le infinite scroll

**Comment by plbabin** [comment]
vue que l'app utilise turbolink je crois pas que ça soit nécessaire

**Comment by gcauchon** [comment]
@remiprev d'où le point d'interrogation!

**Comment by remi** [comment]
> @remiprev d'où le point d'interrogation!

C’est ça, je répondais à ta question avec mon opinion personnelle :smile:

**Comment by Madumo** [comment]
Je suis aussi en train de concocter un template, j'vous le montre d'ici une heure.

**Comment by j15e** [comment]
:-1: pour le infinite scroll too. "Plus de ragout" c'est awesome.

**Comment by gcauchon** [comment]
C'est bien trop vrai; j'avais oublié que le "Plus de ragout" était la pagination!

À ma défence d'avoir mentionné le _infinite-scroll_, je suis sans émotion pour tous les types de pagination qui existent : 
- la pagination traditionnel `[first] [prev] [0] [1] ... [next] [last]` c'est lourd visuellement et surtout contextuellement meaningless.
- le infinite-scroll ou une simple navigation `[prev] [next]`c'est minimaliste. le scroll s'applique plus au mobile vu la largeur de l'écran, mais encore la, dans un context plus sérieux que OCN, prev/next est rarement suffisance si on compare avec l'impression de l'usager que la liste a été chargée en entier!

J'ai rien trouvé qui faisait plus 2013 encore...

En conclusion, pour OCN, "Plus de ragout" c'est :+1:

**Comment by Madumo** [comment]
Ça demande encore un peu de travail, mais qu'en pensez-vous jusqu'à présent?

![demo-app](https://f.cloud.github.com/assets/2637675/1635472/07ddab4c-57af-11e3-9482-8adaba392aac.png)
![demo-mob-2](https://f.cloud.github.com/assets/2637675/1635473/07e5129c-57af-11e3-9842-eda886bb10db.png)
![demo-mob-1](https://f.cloud.github.com/assets/2637675/1635474/07e63a50-57af-11e3-86c5-c7fb26845269.png)

**Comment by Madumo** [comment]
@plbabin j'aime bien comment tu as organisé les posts, j'vais m'en inspirer.

**Comment by louim** [comment]
@j15e, @remiprev par pure curiosité, pourquoi pas de infinite-scroll? Pour la complexité que ça apporte?
@Madumo  j'aime bien ce que je vois! Peut-être ajouter une  séparation entre les post un peu plus définie?

**Comment by Madumo** [comment]
@louim en effet, j'ai pas trop travaillé l'affichage des posts à présent.

**Comment by L-A** [comment]
Je lance une grosse balle courbe: C'est un site de discussion, est-ce qu'il ne serait pas plus efficace de permettre d'en voir une partie au premier niveau? Personne ne nous force à faire comme YC/Reddit et demander de toujours changer de page pour voir les 2 commentaires de chaque post.

Something something wireframe:
![ocn exemple](https://f.cloud.github.com/assets/861964/1647220/fae7fb48-5936-11e3-82ab-647eb09567c3.png)

**Comment by EtienneLem** [comment]
Pourquoi pas! Ça me semble quand même une bonne idée.

Technicalité: PushState quand t’ouvres le “panel” (fack quand tu refresh t’es dans le même state, panel ouvert). En responsive rendu trop petit, tu drop le listing pis tu fais du back ’n forth (w/ PushState on me suit?).

**Comment by Madumo** [comment]
Tu parles bien du truc qui permet de naviguer dans l'historique du browser?

**Comment by plbabin** [comment]
@Madumo oui 

@L-A ça slide left quand on click sur un thread?

@EtienneLem pourquoi pas ouvrir le contenu en dessous du post ? c'est p-e pas efficace par contre (sinon on fait comme tu dis, quand on click et qu'on est dans un viewport trop petit,on laisse le défaut du lien agir)

**Comment by louim** [comment]
Est-ce qu'il y aurait une façon d'accéder au thread en view "full screen"? Si c'est un long post, ou qu'il y a beaucoup de commentaires imbriqués (j'pense pas que ça en vienne comme reddit ou c'est presque impossible de suivre les niveaux d'imbrication tellement il y a de commentaires, mais bon), selon moi ça pourrais être utile. Ou alors une manière de minimiser la colonne de gauche pour avoir plus d'espace pour lire?

**Comment by jpsirois** [comment]
Je viens justement de tomber sur un site qui ressemble beaucoup à ce dont on parle ici. Pour l’inspiration si jamais ça peux servir : http://monocle.io/posts/monocle-has-been-open-sourced (J’ai le lien vers cet article parce qu'il y a des commentaires pour avoir un aperçu.)

**Comment by gcauchon** [comment]
J'aime bien l'idée d'utiliser l'espace horizontale pour présenter un preview dans une colonne à droite! OCN s'adresse aux devs actifs dans la communauté de Québec, on s'entend qu'on travaille tous avec des grosses résolutions alors le _responsiveness_ fait beaucoup de sens, surtout pour conserver une bonne utilisabilité sur les tablets/mobiles!

Ça va prendre un synonyme à "Plus de ragout" pour la colonne de preview par contre! 
- plus de sauce
- plus de ketchup
- etc...

**Comment by EtienneLem** [comment]
Cool! Pour les power users y’a vraiment de quoi à faire: `j`, `k` pour naviguer, `u` pour upvoter, `c` focus le textarea pour commenter, etc :metal:

**Comment by Madumo** [comment]
J'aime bien l'idée de la vue sur le côté. Je pense qu'on devrait aussi afficher la vue sous le post en version petite résolution lorsque les évènements touch sont disponible, et j'ajouterais de la gestuelle qui permettrait de fermer la vue du post en "slidant" vers la gauche. En version large ça fermerait la vue en la glissant vers la liste des posts, et en petite résolution tu la glisses en dehors de l'écran ce qui permettrait aux éléments de la liste de ce rejoindre à nouveau.

Et puis... "Plus de viande". :meat_on_bone:

**Comment by L-A** [comment]
En fait, en version mobile, ça permettrait de garder exactement le même markup et de simplement présenter une des deux moitiés à la fois – largeur oblige. @EtienneLem tu me corrigeras si je dis des imbécilités (also, j'aime l'idée des raccourcis).

@plbabin Gut feeling: je crois pas qu'un slide in/out est approprié dans un viewport large. On s'en sert habituellement pour entretenir une métaphore qui soutient la navigation. Sur mobile il faut évidemment déplacer la vue, mais même si la boîte de droite flash ou fade au reload sur les plus grands écrans, ça devrait pas être dérangeant.

La quantité de commentaires imbriqués reste une question en suspens si on veut leur permettre de faire des accordéons à l'infini. Je serais du genre à essayer un montant arbitraire (3? 4?) au-delà duquel ça reste aligné.

**Comment by garno** [comment]
Nice! Good job guys :) J'adore la vision que vous avez de OCN en colonnes mais je ne crois pas que ce soit une priorité pour lancer rapidement. Pour le moment, je crois qu'on peut y aller avec la version de @Madumo qui est très clean et simple. Si on se lance tout de suite dans la version de @L-A on ne pourrait pas lancer avant plusieurs semaines encore.

Est-ce que ça vous convient?

**Comment by remi** [comment]
> Est-ce que ça vous convient?

C’est toi le boss :smile: Pour vrai, je suis 100% d’accord.

**Comment by plbabin** [comment]
all in

**Comment by jpsirois** [comment]
:+1: C’est ce qui est le plus logique!

**Comment by plbabin** [comment]
@Madumo tu devrais créer une branche pour qu'on puisse t'aider à intégrer le design, à moins que tu as déjà tout fait et qu'il te reste juste à envoyer un PR :)

**Comment by L-A** [comment]
Crime @garno je pensais que la version rapide c'était juste pour le Opencode. Go pour ce que @Madumo a fait, dans ce cas, a va être beaucoup plus efficace. On fera p-e un petit hustle autour des couleurs :)

**Comment by Madumo** [comment]
~~Voilà: https://github.com/Madumo/ocn/tree/new_nav_bar~~

Voilà: https://github.com/Madumo/ocn/tree/redesign

J'aimerais proposer qu'on enlève bootstrap. On en fait presque pas l'utilisation et à toutes les fois que j'veux faire une modif y'a 1000 sélecteurs différents qui s'attaque à l'élément que j'essais de modifier, c'est dérangeant. Aussi j'aime pas trop comment le responsiveness est géré par bootstrap. Je préfèrerais qu'on mette un max-width de 1200px et qu'en dessous de cela le container s'adapte automatiquement à la largeur du viewport avec des medias query qui modifierais uniquement les marges/police mais pas la taille du container.

Bref bootstrap en ce moment c'est plus un bâton dans nos roues qu'une aide précieuse.

**Comment by EtienneLem** [comment]
> Bref bootstrap en ce moment c'est plus un bâton dans nos roues qu'une aide précieuse.

**Bref bootstrap** <del>en ce moment</del> **c'est** <del>plus</del> **un bâton dans** <del>nos</del> **les roues.** <del>qu'une aide précieuse.</del>

Yep :+1:

**Comment by Madumo** [comment]
J'ai merger les dernières modif qu'il y a eu sur master et j'ai donné un nom plus adéquat à la branch. Au départ je voulais juste refaire la nav bar mais mes modifications ont dépassées ce scope.

https://github.com/Madumo/ocn/tree/redesign

**Comment by garno** [comment]
@L-A Oui au départ mais comme j'ai pas réussi à livrer on va se contenter de mettre en ligne et voir si la réponse est bonne avant d'investir du temps de fou :) La version que tu proposes est de loin supérieure mais peu réaliste à court terme.

**Comment by Madumo** [comment]
J'ai fait un pull request pour ma version du design.

@plbabin Ça serait cool si tu pouvais y ajouter les modifications que tu as fait sur la présentation des posts (sans les bordures je dirais, mais bon à toi de voir) ainsi que celles du footer.

@L-A Je vais te laisser faire ta magie de designer pour ce qui est des couleurs ;-)

**Comment by garno** [comment]
Je vais fermer la thread pour là. On a une v1 qui fait du sens niveau design :) Thanks all!
