### ISSUE TITLE
Ne pas afficher les logs d'ActiveRecord lorsque l'on roule les tests

### ISSUE THREAD

**Issue by garno** [opencodeca/ocn#77]
J'ai aucune idée pourquoi ils s'affichent mais c'est irritant.

**Comment by remi** [comment]
Je sais très exactement pourquoi. Je n’ai pas trouvé de solution encore :smile:

**Comment by garno** [comment]
Indice? :) J'ai cherché un peu et je n'ai pas trouvé...

**Comment by pier-oliviert** [comment]
J'étais curieux, et parce que quand j'ai une idée dans tête je l'ai pas dans les pieds, voici la cause. Enlever le gem rails_12factor devrait régler ça. https://github.com/heroku/rails_stdout_logging/blob/master/lib/rails_stdout_logging/rails.rb#L3

**Comment by remi** [comment]
En fait, il faudrait juste la laisser en `production` dans le `Gemfile`.

**Comment by remi** [comment]
Aaaaaand done!

**Comment by pier-oliviert** [comment]
Yes, t'a raison! /Kirk out

**Comment by remi** [comment]
Merci pour le bug hunting! :grinning:
