### ISSUE TITLE
Les dates relatives devraient voir un timestamp absolu dans leur attribut `title`

### ISSUE THREAD

**Issue by remi** [opencodeca/ocn#82]
Facile à faire avec un petit helper qu’on utilise à chaque fois qu’on output une date relative.

**Comment by gcauchon** [comment]
Question d'un gars qui a pas mal moins de web derrière la cravate : est-ce qu'on ne devrait pas gérer le display des dates en JS à la place de le faire backend?

J'utilise habituellement `moment.js` parce que ça se base sur la locale et que c'est facilement paramétrisable; ça s'applique plus facilement dans un mvc JS que dans une webapp server-rendered par contre...

**Comment by remi** [comment]
Je ne trippe pas sur le fait de se fier sur JavaScript pour afficher des dates. Le moins de JS possible :smile:

**Comment by EtienneLem** [comment]
Je trouve que GitHub ont la meilleure solution. La date est géré bothend (lol). Printé serveur (avec un attribut datetime et title) et refreshé en JavaScript.

Ça s’appel le _progressive enhancement_.

**Comment by gcauchon** [comment]
@remiprev je suis curieux de t'entendre expliquer les expériences qui t'ont amenées à ne pas 'tripper' sur JS pour les dates. Sujet intéressant pour un talk; on s'entend qu'afficher des dates, c'est valide pour à peu près tout ce qui se fait sur le web!

@EtienneLem intéressant, je vais regardé ça...

**Comment by remi** [comment]
> @remiprev je suis curieux de t'entendre expliquer les expériences qui t'ont amenées à ne pas 'tripper' sur JS pour les dates. Sujet intéressant pour un talk; on s'entend qu'afficher des dates, c'est valide pour à peu près tout ce qui se fait sur le web!

Je ne trippe pas sur ajouter du JS pour un truc que le backend gère très bien.

**Comment by gcauchon** [comment]
> Je ne trippe pas sur ajouter du JS pour un truc que le backend gère très bien.

Est-ce que ça se gère aussi bien avec de l’`i18n`? J’ai toujours pensé que le backend devait avoir le moins de logique d’affichage possible…

Discussion à suivre en personne!
