### ISSUE TITLE
Ajouter les templates d'erreur pour Gaffe

### ISSUE THREAD

**Issue by garno** [opencodeca/ocn#83]
En production, Gaffe génère des erreurs 500 puisque les templates ne sont pas accessibles.

```
Processing by App::ErrorsController#show as */*                      
  Rendered app/errors/not_found.fr.html.erb within layouts/application
  Rendered shared/_nav.html.erb (66.6ms)                             
Completed 500 Internal Server Error in 74ms                          
```

**Comment by Madumo** [comment]
Est-ce-que l'issue [#102](https://github.com/opencodeqc/ocn/issues/102) est un workaround temporaire à ce problème?

**Comment by remi** [comment]
> Est-ce-que l'issue #102 est un workaround temporaire à ce problème?

Non ce n’est pas relié. Gaffe gère les pages d’erreur, pas les messages d’erreur.

**Comment by Madumo** [comment]
AAAaahhh.

J'ai rien dit alors.

**Comment by remi** [comment]
> En production, Gaffe génère des erreurs 500 puisque les templates ne sont pas accessibles.

Es-tu certain que c’est encore le cas? Je vois bien la page d’erreur 404 → http://ocn-staging.herokuapp.com/foo
