### ISSUE TITLE
Ouvert à dropper Devise?

### ISSUE THREAD

**Issue by pier-oliviert** [opencodeca/ocn#9]
Je ne suis pas certain d'où vous allez avec le projet, mais je vois github-oauth et c'est bundler dans un ActionController action.

Puisque ça utilise request.env[], ça pourrait probablement être placé dans une strategy de warden comme ça, vous garderiez le business logic dans le controller/model et garderais l'authentication pour les strategies.

Je sais pas si vous me suivez, mais en même temps, je veux pas forker et porter à Warden pour rien :)

**Comment by garno** [comment]
Pour le moment, je ne vois pas le gain puisque la création de compte est déjà fonctionnelle et que je préfère faire progresser les autres parties avant de faire du _refactoring_. C'est un peu prématuré mais, si tu y tiens, je ne suis pas nécessairement contre l'idée.

Il faudrait voir le résultat avant de juger ;)

**Comment by pier-oliviert** [comment]
Entre autre, c'est habituellement plus facile à tester des strategies que des tests d'intégrations. J'y tiens pas, c'était une suggestion. On a tous nos définition du refactoring ;) 

Bonne chance.
