### ISSUE TITLE
README.md - Clarifier le setup GitHub OAuth pour le développement localhost

### ISSUE THREAD

**Issue by gcauchon** [opencodeca/ocn#94]
C'est la première webapp pour laquelle j'utilise l'OAuth d'un _3rd party_, comment on fait pour exposer un app local pour les callback URLs d'une [application GitHub](https://github.com/settings/applications)?

J'imagine qu'il y a des tools pour associer un DNS avec une machine local et du port forwarding à faire sur mon de router pour laisser passer les requêtes sur le port `80` !?

**Comment by j15e** [comment]
Pas besoin de rien de ça, t'as juste besoin de setup une key oAuth sur github :

https://github.com/settings/applications/new

**Comment by j15e** [comment]
tu peux mettre http://localhost ça marche

![config](https://f.cloud.github.com/assets/143380/1628698/d517eb2a-571b-11e3-9ec8-2282966828b1.png)

**Comment by gcauchon** [comment]
c'était trop simple pour que j'y pense il faut croire...

**Comment by j15e** [comment]
:+1:
